version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=bet_lottery
     - POSTGRES_USER=bet_lottery
     - POSTGRES_PASSWORD=bet_lottery
     - MAX_CONNECTIONS=50
 event-store:
   image: eventstore/eventstore
   ports:
     - "2113:2113"
     - "1113:1113"